#!/usr/bin/env python3
"""Generate docs/THIRD_PARTY_LICENSES.md from installed package metadata.

Lists the third-party components that ship inside the installers:

* Python packages frozen into the engine (the runtime dependency closure of
  ``livestock-engine``), read from their installed distribution metadata;
* JavaScript packages bundled into the UI (production imports) and the
  Electron runtime, read from ``desktop/node_modules``.

Run it from an environment where the engine is installed and ``npm ci`` has
been run in ``desktop/`` - the same environment used to build installers.
"""

from __future__ import annotations

import json
import re
import sys
from importlib import metadata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "THIRD_PARTY_LICENSES.md"
# Imported by the renderer bundle (see desktop/src/renderer) + the runtime itself.
JS_PACKAGES = ["electron", "react", "react-dom", "scheduler", "leaflet"]
# Build-time only: shipped code does not include them, but they shape the binary.
BUILD_TOOLS = ["pyinstaller", "pyinstaller-hooks-contrib"]

NATIVE_NOTES = [
    ("PROJ (via pyproj wheels)", "MIT", "Coordinate transformation library and proj.db data."),
    ("OpenBLAS (via numpy / scipy wheels)", "BSD-3-Clause", "Linear algebra."),
    ("libgfortran / libquadmath (via scipy wheels, Linux/macOS)", "GPL-3.0 with GCC Runtime Library Exception",
     "Fortran runtime; the exception permits distribution with non-GPL software."),
    ("Chromium (via Electron)", "BSD-3-Clause and others",
     "Full notices ship in every installer as LICENSES.chromium.html."),
    ("PyInstaller bootloader", "GPL-2.0 with bootloader exception",
     "The exception permits distributing frozen applications under any license."),
]


def _requires(dist: metadata.Distribution) -> list[str]:
    names = []
    for req in dist.requires or []:
        if "extra ==" in req:
            continue
        name = re.split(r"[\s;<>=!~\[(]", req, maxsplit=1)[0]
        names.append(name)
    return names


def python_closure(root: str) -> list[metadata.Distribution]:
    seen: dict[str, metadata.Distribution] = {}
    stack = [root]
    while stack:
        name = stack.pop()
        key = name.lower().replace("_", "-")
        if key in seen:
            continue
        try:
            dist = metadata.distribution(name)
        except metadata.PackageNotFoundError:
            continue
        seen[key] = dist
        stack.extend(_requires(dist))
    seen.pop(root, None)
    return sorted(seen.values(), key=lambda d: d.metadata["Name"].lower())


def license_of(dist: metadata.Distribution) -> str:
    md = dist.metadata
    expr = md.get("License-Expression")
    if expr:
        return expr
    classifiers = [c.split("::")[-1].strip() for c in md.get_all("Classifier") or [] if c.startswith("License ::")]
    if classifiers:
        return ", ".join(classifiers)
    text = (md.get("License") or "").strip()
    first = text.splitlines()[0] if text else ""
    return first if len(first) < 80 else first[:77] + "..."


def js_package(name: str) -> tuple[str, str, str] | None:
    path = ROOT / "desktop" / "node_modules" / name / "package.json"
    if not path.exists():
        return None
    pkg = json.loads(path.read_text())
    lic = pkg.get("license") or pkg.get("licenses") or "UNKNOWN"
    if isinstance(lic, list):
        lic = ", ".join(x.get("type", "?") for x in lic)
    return pkg["name"], pkg["version"], str(lic)


def main() -> int:
    py = python_closure("livestock-engine")
    if not py:
        print("livestock-engine is not installed in this environment", file=sys.stderr)
        return 1
    lines = [
        "# Third-party licenses",
        "",
        "Generated by `packaging/third_party_licenses.py` from installed package metadata. Regenerate it",
        "whenever dependencies change (`make licenses`). It lists every third-party component shipped",
        "inside the installers. The project's own license is set by its owner (see docs/HANDOVER.md).",
        "",
        "## Python packages frozen into the engine",
        "",
        "| Package | Version | License |",
        "| --- | --- | --- |",
    ]
    lines += [f"| {d.metadata['Name']} | {d.version} | {license_of(d)} |" for d in py]
    lines += ["", "## JavaScript packages bundled into the app", "", "| Package | Version | License |", "| --- | --- | --- |"]
    for name in JS_PACKAGES:
        info = js_package(name)
        lines.append(f"| {info[0]} | {info[1]} | {info[2]} |" if info else f"| {name} | (not installed) | - |")
    lines += ["", "## Native libraries inside those packages", "", "| Component | License | Notes |", "| --- | --- | --- |"]
    lines += [f"| {n} | {lic} | {note} |" for n, lic, note in NATIVE_NOTES]
    lines += ["", "## Build tools (not shipped as code)", "", "| Package | Version | License |", "| --- | --- | --- |"]
    for name in BUILD_TOOLS:
        try:
            d = metadata.distribution(name)
            lines.append(f"| {d.metadata['Name']} | {d.version} | {license_of(d)} |")
        except metadata.PackageNotFoundError:
            lines.append(f"| {name} | (not installed) | - |")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(py)} Python packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
